name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: e-kotov/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          base: repositories
          config_order: base.repositories, isocalendar, habits, languages, reactions, pagespeed, people, achievements
                    
          plugin_isocalendar: yes
                    
          plugin_habits: yes
          
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_recent_days: 0

          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
        
          plugin_reactions: yes
          
          plugin_pagespeed: yes
          plugin_pagespeed_url: ollieg.codes
          
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
